baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'
sectionPagesMenu = 'main'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Products'
pageRef = '/products'
weight = 20

[[menus.main]]
name = 'Services'
pageRef = '/services'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
